# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:

      # specify the version you desire here
      - image: buildpack-deps:trusty

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: npm install
      - run: npm dev-prod
      - run: npm test

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only:
              - develop
              - feature/*



